version: '3.0'

services:
 vault:
    image: vault
    container_name: vault-net
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    networks:
      - appvault
    ports:
      - 8200:8200
networks:
  appvault:
    name: appvault
    driver: bridge

